CREATE TABLE IF NOT EXISTS Content (
    id INT AUTO_INCREMENT PRIMARY KEY,
    title VARCHAR(255) NOT NULL,
    desc VARCHAR(255),
    url VARCHAR(255),
    status VARCHAR(255),
    content_Type VARCHAR(255) NULL,
    date_Created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    date_Updated TIMESTAMP DEFAULT NULL
);
